config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  devise_for :users, :path => '', :path_names => { :sign_in => "manager", :sign_out => "manager/logout" }, only: [:sessions]
  resources :schedules, only: [:create, :new, :index]
  scope :manager do
    resources :services, :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :service

  validates :owner_name, :phone, :owner_email, :date, :hour, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :schedules
  mount_uploader :image, ImageUploader

  validates :name, :description, :value, :image, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :validatable

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :email, uniqueness: true
  validates :email, :password, presence: true
  validates :password, length: { minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    users_url
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @services = Service.all
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def new
    @schedule = Schedule.new
  end

  def create
    schedule = Schedule.create(schedule_params)
    if schedule.save
      ScheduleMailer.with(schedule: schedule).scheduled_email.deliver_now
      redirect_to root_path, :flash => { :success => "Agendamento feito com sucesso!"}
    else
      redirect_to root_path, :flash => { :danger => "Erro ao tentar realizar o agendamento!"}
    end
  end

  def index
    @schedules = Schedule.all
  end

  private

  def schedule_params
    params.require(:schedule).permit(:owner_name, :phone, :owner_email, :date, :hour, :service_id)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_service, only:[:destroy, :edit, :update]

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def update
    if @service.update(service_params)
      redirect_to services_path, :flash => { :success => "Serviço atualizado com sucesso!"}
    else
      redirect_to edit_service_path, :flash => { :danger => "Erro ao atualizar serviço!"}
    end
  end

  def create
    service = Service.create(service_params)
    if service.save
      redirect_to services_path, :flash => { :success => "Serviço criado com sucesso!"}
    else
      redirect_to new_service_path, :flash => { :danger => "Erro ao criar serviço!"}
    end
  end

  def destroy
    if @service.destroy
      redirect_to services_path, flash: {success: 'Serviço excluido com sucesso!'}
    else
      redirect_to services_path, flash: {danger: 'Erro ao excluir serviço!'}
    end
  end

  private

  def service_params
    params.require(:service).permit(:name, :description, :value, :image)
  end

  def find_service
    @service = Service.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only:[:destroy, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, :flash => { :success => "Usúario atualizado com sucesso!"}
    else
      redirect_to edit_user_path, :flash => { :danger => "Erro ao atualizar usuário!"}
    end
  end

  def create
    user = User.create(user_params)
    if user.save
      redirect_to users_path, :flash => { :success => "Usúario cadastrado com sucesso!"}
    else
      redirect_to new_user_path, :flash => { :danger => "Erro ao criar usuário!"}
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path, flash: {success: 'Usuário excluido com sucesso!'}
    else
      redirect_to users_path, flash: {danger: 'Erro ao excluir usuário!'}
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.erb
<%= render "shared/principal_header" %>
<div class="row">
    <h1>Serviços disponiveis:</h1>
  </div>
  <div class="row">
    <table class="table">
      <tr>
        <th class="text-center" scope="col">Nome</th>
        <th class="text-center" scope="col">Imagem</th>
        <th class="text-center" scope="col">Descrição</th>
        <th class="text-center" scope="col">Valor</th>
        <th class="text-center" scope="col">Ações</th>
      </tr>
      <% @services.each do |service|%>
        <tr>
          <td class="p-5 text-center"><%= service.name %></td>
          <td class="text-center"><img src="<%= service.image.url %>" alt="Teste" width="150" height="150"></td>
          <td class="p-5 text-center"><%= service.description %></td>
          <td class="p-5 text-center"><%= service.value %></td>
          <td class="p-5 d-flex justify-content-center">
            <%= link_to 'Agendar', new_schedule_path(service_id: service), class:'btn btn-primary' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petshop do João</title>
    <%= csrf_meta_tags %>
    <link href="/open-iconic/font/css/open-iconic-bootstrap.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <% if flash[:success] %>
        <div class="mr-auto ml-auto mt-2">
          <div class="alert alert-success"><%= flash[:success] %></div>
        </div>
      <% end %>
      <% if flash[:danger] %>
        <div class="mr-auto ml-auto mt-2">
          <div class="alert alert-danger"><%= flash[:danger] %></div>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/schedules/index.erb
<%= render "shared/header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h1> Listagem de Agendamentos </h1>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table">
      <tr>
        <th class="text-center" scope="col">Nome do dono</th>
        <th class="text-center" scope="col">Telefone</th>
        <th class="text-center" scope="col">Email do dono</th>
        <th class="text-center" scope="col">Data</th>
        <th class="text-center" scope="col">Hora</th>
        <th class="text-center" scope="col">Serviço</th>
      </tr>
      <% @schedules.each do |schedule| %>
        <tr>
          <td class="text-center"><%= schedule.owner_name %></td>
          <td class="text-center"><%= schedule.phone %></td>
          <td class="text-center"><%= schedule.owner_email %></td>
          <td class="text-center"><%= schedule.date %></td>
          <td class="text-center"><%= schedule.hour %></td>
          <td class="text-center"><%= schedule.service.name %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/schedules/new.erb
<%= render "shared/principal_header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h2>Agendar</h2>
  </div>
</div>
<div class="row">
  <%= form_for @schedule, html: {class: "col"} do |f|%>
    <%= f.hidden_field :service_id, value: params[:service_id], class: 'form-control' %>
    <div class="form-group">
      <%= label_tag :owner_name, "Nome do dono" %>
      <%= f.text_field :owner_name, class: "form-control", required: true  %>
    </div>
    <div class="form-group">
      <%= label_tag :phone, "Telefone" %>
      <%= f.text_field :phone, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= label_tag :owner_email, "Email do dono" %>
      <%= f.text_field :owner_email, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= label_tag :date, "Data" %>
      <%= f.date_field :date, class: "form-control", required: true %>
    </div>
    <div class="form-group">
      <%= label_tag :hour, "Hora" %>
      <%= f.time_field :hour, class: "form-control", required: true %>
    </div>
    <%= f.submit 'Agendar', class: "btn btn-primary"%>
  <% end %>
</div>

app/views/services/_form.erb
<%= form_for @service, html: {class: "mr-auto ml-auto"} do |f|%>
  <div class="form-group">
    <%= label_tag :name, "Nome do serviço" %>
    <%= f.text_field :name, class: "form-control", required: true  %>
  </div>
  <div class="form-group">
    <%= label_tag :description, "Descrição" %>
    <%= f.text_area :description, class: "form-control",  required: true  %>
  </div>
  <div class="form-group">
    <%= label_tag :value, "Valor" %>
    <%= f.number_field :value, class: "form-control",  required: true, step: :any  %>
  </div>
  <div class="form-group">
    <%= label_tag :image, "Imagem do serviço" %>
    <%= f.file_field :image, class: "form-control",  required: true  %>
  </div>
  <%= f.submit button, class: "btn btn-primary"%>
<% end %>

app/views/services/edit.erb
<%= render "shared/header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h2>Edição de Serviços</h2>
  </div>
</div>
<div class="row">
  <%= render partial: 'form', locals: { button: 'Editar Serviço' }%>
</div>

app/views/services/index.erb
<%= render "shared/header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h1> Listagem de Serviços </h1>
  </div>
</div>
<div class="row">
  <div class="col">
    <%= link_to 'Cadastrar serviço', new_service_path, class:'float-right btn btn-primary mb-1'%>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table">
      <tr>
        <th class="text-center" scope="col">Imagem</th>
        <th class="text-center" scope="col">Nome</th>
        <th class="text-center" scope="col">Descrição</th>
        <th class="text-center" scope="col">Valor</th>
        <th class="text-center" scope="col">Ações</th>
      </tr>
      <% @services.each do |service| %>
        <tr>
          <td class="text-center"><img src="<%= service.image.url %>" alt="Teste" width="150" height="150"></td>
          <td class="p-5 text-center"><%= service.name %></td>
          <td class="p-5 text-center"><%= service.description %></td>
          <td class="p-5 text-center"><%= service.value %></td>
          <td class="p-5 d-flex justify-content-center">
            <%= link_to 'Editar', edit_service_path(service.id), class:'btn btn-primary' %>
            <%= link_to 'Excluir', service, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: ' ml-1 btn btn-danger'%>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/services/new.erb
<%= render "shared/header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h2>Cadastro de Serviço</h2>
  </div>
</div>
<div class="row">
  <%= render partial: 'form', locals: { button: 'Adicionar Serviço' } %>
</div>

app/views/shared/_header.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Serviços
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Cadastrar", new_service_path, class: "dropdown-item" %>
          <%= link_to "Listar", services_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Usuarios
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Cadastrar", new_user_path, class: "dropdown-item" %>
          <%= link_to "Listar", users_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Agendamentos", schedules_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Deslogar", destroy_user_session_path, method: 'delete', class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_principal_header.erb
<header class="row bg-light">
  <div class="col text-center">
    <h1>Petshop do João</h1>
  </div>
</header>

app/views/users/_form.erb
<%= form_for @user, html: {class: "mr-auto ml-auto"} do |f|%>
  <div class="form-group">
    <%= label_tag :email, "Email" %>
    <%= f.text_field :email, class: "form-control", required: true  %>
  </div>
  <div class="form-group">
    <%= label_tag :password, "Senha" %>
    <%= f.password_field :password, class: "form-control", required: true %>
  </div>
  <%= f.submit button, class: "btn btn-primary"%>
<% end %>

app/views/users/edit.erb
<%= render "shared/header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h2>Edição de Usuários</h2>
  </div>
</div>
<div class="row">
  <%= render partial: 'form', locals: { button: 'Editar Usuário' }%>
</div>

app/views/users/index.erb
<%= render "shared/header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h1> Listagem de Usuários </h1>
  </div>
</div>
<div class="row">
  <div class="col">
    <%= link_to 'Cadastrar usuário', new_user_path, class:'float-right btn btn-primary mb-1'%>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table">
      <tr>
        <th class="text-center" scope="col">ID</th>
        <th class="text-center" scope="col">Email</th>
        <th class="text-center" scope="col">Ações</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td class="text-center"><%= user.id %></td>
          <td class="text-center"><%= user.email %></td>
          <td class="d-flex justify-content-center">
            <%= link_to 'Editar', edit_user_path(user.id), class:'btn btn-primary' %>
            <%= link_to 'Excluir', user, method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: 'ml-1 btn btn-danger'%>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/new.erb
<%= render "shared/header" %>
<div class="row">
  <div class="ml-auto mr-auto">
    <h2>Cadastro de Usuários</h2>
  </div>
</div>
<div class="row">
  <%= render partial: 'form', locals: { button: 'Criar Usuário' } %>
</div>